version: '3'

services:
   db:
     image: mongo:latest
     volumes:
       - db_data:/data/db
     restart: always
   
   clonecord-server:
     depends_on:
       - db
     image: clonecord-server:latest
     ports:
       - "8080:8080"
     restart: always
     environment:
       MONGODB_HOST: db
volumes:
    db_data:
